CREATE TABLE IF NOT EXISTS ALUMNO(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MATRICULA VARCHAR(12) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO_PATERNO VARCHAR(100) NOT NULL,
    APELLIDO_MATERNO VARCHAR(50) NOT NULL,
    CARRERA_ID BIGINT NOT NULL
);