CREATE TABLE IF NOT EXISTS ALUMNO(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MATRICULA VARCHAR(12) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO_PATERNO VARCHAR(100) NOT NULL,
    APELLIDO_MATERNO VARCHAR(50) NOT NULL,
    CARRERA_ID BIGINT NOT NULL
);

INSERT INTO ALUMNO(ID, MATRICULA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CARRERA_ID) VALUES
(1, '1712100276', 'KAREN KIM', 'VAZQUEZ', 'ANGELES', 1);
INSERT INTO ALUMNO(ID, MATRICULA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CARRERA_ID) VALUES
(2, '1712100277', 'ROBERTO', 'OLGUIN', 'LOZANO', 1);