INSERT INTO ALUMNO(ID, MATRICULA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CARRERA_ID) VALUES
(1, '1712100276', 'KAREN KIM', 'VAZQUEZ', 'ANGELES', 1);
INSERT INTO ALUMNO(ID, MATRICULA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CARRERA_ID) VALUES
(2, '1712100277', 'ROBERTO', 'OLGUIN', 'LOZANO', 1);