CREATE TABLE IF NOT EXISTS CARRERA(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_CARRERA VARCHAR(80) NOT NULL
);
INSERT INTO CARRERA(ID, NOMBRE_CARRERA)VALUES
(1, 'TIC'),
(2, 'MECANICA'),
(3, 'ENFERMERIA');