CREATE TABLE IF NOT EXISTS CUATRIMESTREMATERIA(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PERIODO_PERSONAL_ID BIGINT NOT NULL,
    CUATRIMESTRE_ID BIGINT NOT NULL,
    GRUPO_ID BIGINT NOT NULL,
    MATERIA_ID BIGINT NOT NULL,
    CARRERA_ID BIGINT NOT NULL
);