CREATE TABLE IF NOT EXISTS CUATRIMESTRE(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUATRIMESTRE VARCHAR(5) NOT NULL
);

INSERT INTO CUATRIMESTRE(ID, CUATRIMESTRE)VALUES
(1, '7MO'),
(2, '8VO'),
(3, '9NO'),
(4, '10MO');