CREATE TABLE IF NOT EXISTS DIRECTOR(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PERIODO_PERSONAL_ID BIGINT NOT NULL,
    CARRERA_ID BIGINT NOT NULL
);

INSERT INTO DIRECTOR(ID, PERIODO_PERSONAL_ID, CARRERA_ID)VALUES
(1,1,1);

