CREATE TABLE IF NOT EXISTS MATERIA(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MATERIA VARCHAR(60) NOT NULL
);

INSERT INTO MATERIA(ID, MATERIA) VALUES
(1, 'INFORMATICA'),
(2, 'APLICACIONES MOVILES'),
(3, 'CALCULO');
