CREATE TABLE IF NOT EXISTS PERIODOALUMNO(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PERIODO_ID BIGINT NOT NULL,
    ALUMNO_ID BIGINT NOT NULL,
    GRADO_ID BIGINT NOT NULL,
    GRUPO_ID BIGINT NOT NULL
);

INSERT INTO PERIODOALUMNO(ID, PERIODO_ID, ALUMNO_ID, GRADO_ID, GRUPO_ID)VALUES
(1,1,1,1,1);