CREATE TABLE IF NOT EXISTS PERIODO(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_PERIODO VARCHAR(80) NULL,
    FECHA_INICIO TIMESTAMP NOT NULL,
    FECHA_FIN TIMESTAMP NOT NULL,
    ESTADO_PERIODO VARCHAR(10) NOT NULL
);

INSERT INTO PERIODO(ID, NOMBRE_PERIODO, FECHA_INICIO, FECHA_FIN, ESTADO_PERIODO) VALUES
(1, 'ENE-ABR', TIMESTAMP '2015-01-01 13:34:19.591', TIMESTAMP '2015-05-01 13:34:19.591', 'ACTIVO');