CREATE TABLE IF NOT EXISTS PERIODOALUMNO(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PERIODO_ID BIGINT NOT NULL,
    ALUMNO_ID BIGINT NOT NULL,
    CUATRIMESTRE_ID BIGINT NOT NULL,
    GRUPO_ID BIGINT NOT NULL
);