CREATE TABLE IF NOT EXISTS PERIODO(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_PERIODO VARCHAR(80) NULL,
    FECHA_INICIO TIMESTAMP NOT NULL,
    FECHA_FIN TIMESTAMP NOT NULL,
    ESTADO_PERIODO VARCHAR(10) NOT NULL
);