CREATE TABLE IF NOT EXISTS PERIODOPERSONAL(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
     PERIODO_ID BIGINT NOT NULL,
     PERSONAL_ID BIGINT NOT NULL,
     PLAN_ID BIGINT NOT NULL
);

INSERT INTO PERIODOPERSONAL(ID, PERIODO_ID, PERSONAL_ID, PLAN_ID)VALUES
(1,1,1,1),
(2,1,2,1),
(3,1,4,1);