CREATE TABLE IF NOT EXISTS PERIODOPERSONAL(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
     PERIODO_ID BIGINT NOT NULL,
     PERSONAL_ID BIGINT NOT NULL,
     CARRERA_ID BIGINT NOT NULL,
     PERFIL VARCHAR(15) NOT NULL,
     PLAN_ID BIGINT NOT NULL
);

INSERT INTO PERIODOPERSONAL(ID, PERIODO_ID, PERSONAL_ID, CARRERA_ID, PERFIL, PLAN_ID)VALUES
(1,1,1,1,'PROFESOR',1);