INSERT INTO PERSONAL(ID, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO) VALUES
(2, 'GAMALIEL', 'VAZQUEZ', 'ZUÑIGA'),
(1, 'JORGE', 'PEREZ', 'PEREZ'),
(3, 'JUAN', 'CRUZ', 'CRUZ'),
(4, 'JOSE', 'SOTO', 'SOTO'),
(5, 'JAIME', 'URIBE', 'URIBE');