CREATE TABLE IF NOT EXISTS PLANDETALLE(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACTIVIDAD VARCHAR(100),
    PROPOSITO VARCHAR(300),
    MES VARCHAR(10) NOT NULL,
    PLAN_ID BIGINT NOT NULL
);

INSERT INTO PLANDETALLE(ID, ACTIVIDAD, MES, PLAN_ID) VALUES
(1, 'EXAMEN EXTRAORDINARIO', 'MES2', 1);