CREATE TABLE IF NOT EXISTS PLAN(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DIAGNOSTICO VARCHAR(300),
    PROPOSITO VARCHAR(300),
    MEDIDAS VARCHAR(300),
    RECOMENDACIONES VARCHAR(300),
    TUTOR_ID BIGINT NULL
);