CREATE TABLE IF NOT EXISTS PLAN(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DIAGNOSTICO VARCHAR(300),
    PROPOSITO VARCHAR(300),
    MEDIDAS VARCHAR(300),
    RECOMENDACIONES VARCHAR(300),
    PERIODO_ID BIGINT NOT NULL
);

INSERT INTO PLAN(ID, DIAGNOSTICO, PROPOSITO, MEDIDAS, RECOMENDACIONES, PERIODO_ID) VALUES
(1, 'BIEN', 'BIEN', 'BIEN', 'BIEN', 1);