CREATE TABLE IF NOT EXISTS TUTORIA(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PERIODO_ALUMNO_ID BIGINT NOT NULL,
    TIPO_TUTORIA VARCHAR(20) NOT NULL,
    STATUS_TUTORIA VARCHAR(20) NOT NULL,
    FECHA_INICIO TIMESTAMP NOT NULL,
    FECHA_FIN TIMESTAMP NOT NULL,
    CANALIZADOR_ID BIGINT NOT NULL,
    TUTOR_ID BIGINT NOT NULL,
    DEPARTAMENTO BIGINT NOT NULL
);

INSERT INTO TUTORIA(ID, PERIODO_ALUMNO_ID, TIPO_TUTORIA, STATUS_TUTORIA, FECHA_INICIO, FECHA_FIN, CANALIZADOR_ID, TUTOR_ID, DEPARTAMENTO) VALUES
(1, 1, 'PREVENTIVA', 'ENPROCESO', TIMESTAMP '2015-02-01 13:34:19.591',TIMESTAMP '2015-02-24 13:34:19.591', 1, 1, 1);