CREATE TABLE IF NOT EXISTS TUTORIA(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PERIODO_ALUMNO_ID BIGINT NOT NULL,
    TIPO_TUTORIA VARCHAR(20) NOT NULL,
    STATUS_TUTORIA VARCHAR(20) NOT NULL,
    FECHA_INICIO TIMESTAMP NOT NULL,
    FECHA_FIN TIMESTAMP NOT NULL,
    CANALIZADOR_ID BIGINT NOT NULL,
    TUTOR_ID BIGINT NOT NULL,
    DEPARTAMENTO BIGINT NOT NULL
);