CREATE TABLE IF NOT EXISTS TUTORIADETALLE(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TUTORIA_ID BIGINT NOT NULL,
    COMENTARIO VARCHAR(350) NOT NULL,
    TIPOCOMENTARIO VARCHAR(30) NOT NULL,
    REGISTRADO_POR_ID INTEGER NOT NULL
);