CREATE TABLE IF NOT EXISTS USER (
    USERNAME VARCHAR(25) PRIMARY KEY,
    PASSWORD VARCHAR(70) NOT NULL,
    ENABLED BIT NOT NULL,
    PERSONAL_ID BIGINT NOT NULL
);
               
INSERT INTO USER (USERNAME, PASSWORD, ENABLED, PERSONAL_ID) VALUES
('jperez', '123456', 1, 2),
('jcruz', '123456', 1, 3),
('jvazquez', '$2a$10$GqqtbEuDi8YXzI1n8Zoqv.Upp61NP/Jy1fvPiMAgtcsyFuwc7N.AK', 1, 1);

CREATE TABLE IF NOT EXISTS USER_ROLE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(25) NOT NULL,
    ROLE VARCHAR(25) NOT NULL
);

INSERT INTO USER_ROLE (ID, USERNAME, ROLE) VALUES
(1, 'jperez', 'ADMIN'),
(2, 'jcruz', 'ADMIN'),
(3, 'jvazquez', 'GERENTE');